// Product catalog — images served locally from /public/products/
export const PRODUCTS = [
  {
    id: 1,
    slug: 'bac-water-30ml',
    name: 'BAC Water 30ML',
    price: 20.00,
    category: 'supplies',
    image: '/products/bac-water.jpg',
    description: 'Bacteriostatic Water for Injection, USP. 30mL multiple-dose vial. Used for reconstituting research peptides.',
    inStock: true,
  },
  {
    id: 2,
    slug: 'wolverine-blend',
    name: 'Wolverine Blend',
    price: 105.00,
    category: 'blends',
    image: '/products/wolverine-blend.jpg',
    description: 'BPC157 / TB500 — 10MG/10MG. A powerful blend combining BPC-157 and TB-500 for research purposes.',
    inStock: true,
  },
  {
    id: 3,
    slug: 'glow-blend',
    name: 'Glow Blend',
    price: 135.00,
    category: 'blends',
    image: '/products/glow-blend.jpg',
    description: 'BPC157 / TB500 / GHK-CU — 70MG. Triple-blend formulation for advanced research applications.',
    inStock: true,
  },
  {
    id: 4,
    slug: 'cjc1295nodac-ipamorelin',
    name: 'CJC1295(NoDac) / Ipamorelin',
    price: 78.00,
    category: 'peptides',
    image: '/products/cjc1295.jpg',
    description: 'CJC1295 No DAC + IPA — 5MG/5MG. Growth hormone releasing peptide blend for research use.',
    inStock: true,
  },
  {
    id: 5,
    slug: 'mots-c',
    name: 'MOTS-C',
    price: 48.00,
    category: 'peptides',
    image: '/products/mots-c.jpg',
    description: 'MOTS-C 10MG. Mitochondrial-derived peptide for metabolic research applications.',
    inStock: true,
  },
  {
    id: 6,
    slug: 'ghk-cu',
    name: 'GHK-CU',
    price: 46.00,
    category: 'peptides',
    image: '/products/ghk-cu.jpg',
    description: 'GHK-Cu 50MG. Copper peptide with broad research applications.',
    inStock: true,
  },
  {
    id: 7,
    slug: 'slu-pp-332',
    name: 'SLU-PP-332',
    price: 250.00,
    category: 'peptides',
    image: '/products/slu-pp-332.jpg',
    description: 'SLU-PP-332. Novel research compound for scientific study.',
    inStock: true,
  },
  {
    id: 8,
    slug: '5-amino-1mq',
    name: '5-Amino-1MQ',
    price: 50.00,
    category: 'peptides',
    image: '/products/5-amino-1mq.jpg',
    description: '5-Amino-1MQ 50MG. Small molecule NNMT inhibitor for metabolic research.',
    inStock: true,
  },
  {
    id: 9,
    slug: 'tesamorelin',
    name: 'Tesamorelin',
    price: 85.00,
    category: 'peptides',
    image: '/products/tesamorelin.jpg',
    description: 'Tesamorelin. Growth hormone releasing factor analogue for research purposes.',
    inStock: true,
  },
  {
    id: 10,
    slug: 'ipamorelin',
    name: 'Ipamorelin',
    price: 70.00,
    category: 'peptides',
    image: '/products/ipamorelin.jpg',
    description: 'Ipamorelin. Selective growth hormone secretagogue for research applications.',
    inStock: true,
  },
  {
    id: 11,
    slug: 'klow-blend',
    name: 'Klow Blend',
    price: 185.00,
    category: 'blends',
    image: '/products/klow-blend.jpg',
    description: 'BPC157 / TB500 / GHK-CU / KPV — 80MG. Advanced quad-blend for comprehensive research.',
    inStock: true,
  },
  {
    id: 12,
    slug: 'thymosin-alpha-1-10mg',
    name: 'Thymosin Alpha-1 10MG',
    price: 78.00,
    category: 'peptides',
    image: '/products/thymosin-alpha-1.jpg',
    description: 'Thymosin Alpha-1 10MG. Immune-modulating peptide for research use.',
    inStock: true,
  },
  {
    id: 13,
    slug: 'bpc-157',
    name: 'BPC-157',
    price: 70.00,
    category: 'peptides',
    image: '/products/bpc-157.jpg',
    description: 'BPC-157. Body Protection Compound peptide for research applications.',
    inStock: true,
  },
  {
    id: 14,
    slug: 'tb-500',
    name: 'TB-500',
    price: 70.00,
    category: 'peptides',
    image: '/products/tb-500.jpg',
    description: 'TB-500 (Thymosin Beta-4). Synthetic peptide for tissue repair research.',
    inStock: true,
  },
  {
    id: 15,
    slug: 'epithalon-50mg',
    name: 'Epithalon 50MG',
    price: 140.00,
    category: 'peptides',
    image: '/products/epithalon.jpg',
    description: 'Epithalon 50MG. Tetrapeptide for longevity and telomere research.',
    inStock: true,
  },
  {
    id: 16,
    slug: 'pinealon-20mg',
    name: 'Pinealon 20MG',
    price: 75.00,
    category: 'peptides',
    image: '/products/pinealon.jpg',
    description: 'Pinealon 20MG. Neuroprotective tripeptide for neurological research.',
    inStock: true,
  },
  {
    id: 17,
    slug: '5-amino-1mq-capsules',
    name: '5-Amino-1MQ Capsules',
    price: 175.00,
    category: 'capsules',
    image: '/products/5-amino-1mq-capsules.jpg',
    description: '5-Amino-1MQ in convenient oral capsule form. Oral NNMT inhibitor for research.',
    inStock: true,
  },
  {
    id: 18,
    slug: 'bpc-157-500mcg-tablets',
    name: 'BPC-157 500MCG Tablets',
    price: 0.00,
    category: 'tablets',
    image: '/products/bpc-157-tablets.jpg',
    description: 'BPC-157 500MCG oral tablets. Coming soon.',
    inStock: false,
  },
  {
    id: 19,
    slug: 'hgh-191aa-10iu-x-10-vials',
    name: 'HGH 191AA (10IU x 10 Vials)',
    price: 220.00,
    category: 'peptides',
    image: '/products/hgh-191aa.jpg',
    description: 'HGH 191AA — 10IU x 10 Vials. Recombinant human growth hormone for research purposes.',
    inStock: true,
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null
}

export function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category)
}

export function formatPrice(price) {
  if (price === 0) return 'Coming Soon'
  return `$${price.toFixed(2)}`
}
