// Product catalog — images served locally from /public/products/
//
// Optional fields (added with the Lab feature):
//   hidden:   boolean — if true, product only appears in /lab (behind a code).
//             Omitted/undefined means the product behaves as a normal Shop item.
//   qbo_name: string  — override name used when syncing the order to QuickBooks.
//             Use this when the website display name differs from the actual
//             QBO inventory item name (so invoices still match inventory and
//             stock decrements correctly). Falls back to `name` if omitted.
export const PRODUCTS = [
  {
    id: 1,
    slug: 'bac-water-30ml',
    name: 'BAC Water 30ML',
    price: 20.00,
    category: 'supplies',
    image: '/products/bac-water.jpg',
    tagline: 'BAC Water 30ML. Bacteriostatic Water supplied in a USP-compliant multi-dose vial (flip top) manufactured by Pfizer. Designed for use in reconstituting lyophilized peptides and other research substances.',
    description: 'Bacteriostatic Water (BAC Water) is a sterile diluent designed for laboratory use in reconstituting lyophilized peptides and other research substances. It contains 0.9% benzyl alcohol, which inhibits bacterial growth, allowing multiple withdrawals from the same vial for ongoing experimental applications. It is the standard choice for peptide reconstitution due to its ability to preserve sterility across multiple uses.',
    additionalInfo: 'USP-grade sterile, non-pyrogenic, pH typically 5.7, in a USP-compliant multi-dose vial (flip top) manufactured by Pfizer. Intended for reconstitution or dilution of injectable substances.',
    mechanisms: [],
    technicalData: [
      'Benzyl Alcohol: 0.9%',
      'Grade: USP sterile, non-pyrogenic',
      'pH: Typically 5.7',
      'Vial: Multi-dose flip top, Pfizer',
      'Storage: Store at 20–25°C (68–77°F); protect from freezing. Keep refrigerated after opening.',
    ],
    coas: [],
    inStock: true,
  },
  {
    id: 2,
    slug: 'wolverine-blend',
    name: 'Wolverine Blend',
    price: 105.00,
    category: 'blends',
    image: '/products/wolverine-blend.jpg',
    tagline: 'Wolverine Blend (BPC-157 10MG / TB-500 10MG). This research only product is supplied in a 3ml vial containing 20mg total — BPC-157 (10mg) and TB-500 (10mg) — as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'The Wolverine Blend combines BPC-157 and TB-500, two peptides extensively studied in animal models for their complementary regenerative properties. BPC-157 (Body Protection Compound) is researched for its effects on tissue repair, inflammation reduction, and gastrointestinal health. TB-500 (Thymosin Beta-4) is studied for its role in healing tendons, ligaments, and muscles. Together they are hypothesized to act synergistically across multiple tissue repair pathways.',
    additionalInfo: '',
    mechanisms: [
      'BPC-157 – Tissue Repair: Promotes angiogenesis and upregulates growth hormone receptors in tendon fibroblasts, accelerating repair in connective and mucosal tissue.',
      'BPC-157 – Anti-Inflammatory: Modulates nitric oxide signaling and suppresses inflammatory cytokines, reducing local and systemic inflammation in preclinical models.',
      'TB-500 – Actin Regulation: Binds to actin monomers via its Ac-LKKTETQ sequence, promoting cell migration, proliferation, and differentiation essential for wound healing.',
      'TB-500 – Musculoskeletal Recovery: Shown in animal studies to improve recovery of tendons, ligaments, and muscle tissue following injury.',
      'Synergistic Effect: The two peptides are hypothesized to target complementary healing pathways — BPC-157 acting more locally and TB-500 providing systemic tissue repair signaling.',
    ],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₂₂₁H₃₄₂N₄₆O₆₈ (combined)',
      'Storage: Protect from light and moisture, keep tightly sealed. Refrigerate reconstituted solution.',
    ],
    coas: [
      { text: 'View Certificate of Analysis – Batch 012601', href: 'https://www.forgeamino.com/s/FA-BPTB012601.pdf' },
      { text: 'View Certificate of Analysis – Batch 022601', href: 'https://www.forgeamino.com/s/FA-BPTB022601.pdf' },
    ],
    inStock: true,
  },
  {
    id: 3,
    slug: 'glow-blend',
    name: 'GLOW Blend',
    price: 135.00,
    category: 'blends',
    image: '/products/glow-blend.jpg',
    tagline: 'GLOW Blend (GHK-Cu 50mg, BPC-157 10mg, TB-500 10mg). This research only product is supplied in a 3ml vial containing a blend of GHK-Cu 50mg, BPC-157 10mg and TB-500 10mg (GLOW 70mg) as a lyophilized powder. The powder will generally have a purple color due to the copper content. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'GLOW Blend is an injectable research formulation combining three peptides — BPC-157, TB-500 (Thymosin Beta-4 fragment), and GHK-Cu — studied for their complementary roles in skin rejuvenation, tissue repair, inflammation reduction, and healing. BPC-157 is a gastric-derived peptide researched for tissue healing, gut repair, and blood vessel formation. TB-500 regulates inflammation, enhances cellular repair, and promotes tissue regeneration and flexibility. GHK-Cu (Copper Tripeptide-1) stimulates collagen production, supports skin remodeling, reduces oxidative stress, and contributes to a brighter, more resilient complexion.',
    additionalInfo: '',
    mechanisms: [
      'BPC-157 – Tissue & Gut Repair: Promotes angiogenesis and upregulates growth hormone receptors in fibroblasts, supporting repair of connective, mucosal, and gastrointestinal tissue.',
      'TB-500 – Cellular Repair & Mobility: Binds actin monomers via its Ac-LKKTETQ sequence to drive cell migration, proliferation, and differentiation. Reduces inflammation and improves tissue regeneration and flexibility.',
      'GHK-Cu – Skin Remodeling: Activates collagen and glycosaminoglycan synthesis, upregulates antioxidant enzymes, and promotes skin remodeling and wound healing via copper-dependent enzymatic processes.',
      'Synergistic Blend: The three peptides act on complementary pathways — deep tissue repair (BPC-157), systemic healing signaling (TB-500), and dermal regeneration (GHK-Cu) — making the combination of interest for skin and connective tissue research.',
    ],
    technicalData: [
      'Form: Lyophilized powder (typically purple in color due to copper)',
      'GHK-Cu Molecular Formula: C₁₄H₂₃CuN₆O₄',
      'BPC-157 Molecular Formula: C₆₂H₉₈N₁₆O₂₂',
      'TB-500 Molecular Formula: C₂₁₂H₃₅₀N₅₆O₇₈S',
      'Storage: Protect from light and moisture, keep tightly sealed. Refrigerate reconstituted solution.',
    ],
    coas: [
      { text: 'View Certificate of Analysis – Batch 012601', href: 'https://www.forgeamino.com/s/FA-GLW012601.pdf' },
      { text: 'View Certificate of Analysis – Batch 022601', href: 'https://www.forgeamino.com/s/FA-GLW022601.pdf' },
      { text: 'View Certificate of Analysis – Batch 032602', href: 'https://www.forgeamino.com/s/COA012-2-IF-824-QSA-TR006-BTL2612-2-CoA-Forge-Amino-BPC-157-TB500-GHK-Cu-FA-GLW032602_signed-2.pdf' },
    ],
    inStock: true,
  },
  {
    id: 4,
    slug: 'cjc1295nodac-ipamorelin',
    name: 'CJC1295(NoDac) / Ipamorelin',
    price: 78.00,
    category: 'peptides',
    image: '/products/cjc1295.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing CJC-1295 without Drug Affinity Complex (noDAC) 5mg and Ipamorelin 5mg as a lyophilized powder. CJC-1295 no DAC is also known as Modified GRF1-29. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'CJC-1295 is a synthetic secretagogue peptide that mimics growth hormone-releasing hormone (GHRH). It binds to pituitary receptors to stimulate GH secretion, which in turn increases insulin-like growth factor-1 (IGF-1) levels. Ipamorelin is a pentapeptide that mimics ghrelin, targeting ghrelin receptors to stimulate GH release without affecting cortisol or prolactin levels.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: CJC-1295 no DAC: C₁₅₂H₂₅₂N₄₄O₄₂ / Ipamorelin: C₃₈H₄₉N₉O₅',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View COA (Batch 022601)', href: 'https://www.forgeamino.com/s/FA-CJCIP022601.pdf' },
      { text: 'View COA (Batch 032601)', href: 'https://www.forgeamino.com/s/COA-CJCIPA-FA-032601.pdf' },
    ],
    inStock: true,
  },
  {
    id: 5,
    slug: 'mots-c',
    name: 'MOTS-C',
    price: 48.00,
    category: 'peptides',
    image: '/products/mots-c.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg MOTS-C as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'MOTS-C is a 16-amino-acid mitochondrial-derived peptide encoded by the mitochondrial 12S rRNA gene (MT-RNR1), discovered in 2015, that regulates cellular metabolism, particularly glucose uptake and fat oxidation in skeletal muscle. It activates AMPK (AMP-activated protein kinase), a key energy-sensing enzyme, promoting insulin sensitivity, mitochondrial function, and adaptation to metabolic stress like exercise. Levels rise with physical activity, mimicking its effects. MOTS-C translocates to the cell nucleus to influence gene expression for metabolic homeostasis, which declines with age, sparking interest in anti-aging and performance.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₁₀₁H₁₅₂N₂₈O₂₂S₂',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View Certificate of Analysis', href: 'https://www.forgeamino.com/s/FA-MOT012601-gkt5.pdf' },
    ],
    inStock: true,
  },
  {
    id: 6,
    slug: 'ghk-cu',
    name: 'GHK-CU',
    price: 46.00,
    category: 'peptides',
    image: '/products/ghk-cu.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 50mg GHK-Cu as a lyophilized powder. GHK-Cu typically has a purple color due to the copper content. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'GHK-Cu (glycine-histidine-lysine copper peptide) is a naturally occurring tripeptide complex. This copper-binding peptide plays roles in wound healing, tissue regeneration, and anti-inflammatory processes. GHK-Cu stimulates collagen and elastin production while providing antioxidant protection. It promotes angiogenesis and helps regulate remodeling in damaged tissues. Due to these properties, GHK-Cu is widely used in anti-aging skincare formulations and is being studied for potential applications in wound healing, hair growth, and tissue regeneration.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₁₄H₂₄N₆O₄',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View Certificate of Analysis', href: 'https://www.forgeamino.com/s/FA-GHK012601.pdf' },
    ],
    inStock: true,
  },
  {
    id: 7,
    slug: 'slu-pp-332',
    name: 'SLU-PP-332',
    price: 250.00,
    category: 'peptides',
    image: '/products/slu-pp-332.jpg',
    tagline: 'SLU-PP-332 is provided in 1mg per tablet oral tablets packaged 100 tablets per bottle. It is considered a small molecule and not technically a peptide. The compound is manufactured and handled according to internal quality standards designed to support consistency, identity, and integrity for research workflows.',
    description: 'SLU-PP-332 is a synthetic compound that functions as a potent estrogen-related receptor (ERR) agonist, acting most strongly at ERRα with an EC50 of 98 nM. It is classified as an exercise mimetic, meaning it replicates the metabolic benefits of physical activity without requiring actual exercise.',
    additionalInfo: '',
    mechanisms: [
      'Metabolic improvements: Counteracts metabolic syndrome in mice and normalizes metabolic profiles in cardiac tissue.',
      'Muscle enhancement: Increases type IIa muscle fibers with high capacity for breaking down sugars and fats, while inducing an exercise-like genetic program that improves endurance.',
      'Thermogenesis: Increases brown adipose tissue (BAT) activity by 50% in mice.',
      'Mitochondrial function: Increases mitochondrial DNA by 2.5-fold and enhances cellular respiration.',
      'Anti-aging markers: Reverses inflammatory and aging markers in preclinical studies.',
    ],
    mechanismsLabel: 'Preclinical Effects',
    technicalData: [
      'Form: Oral tablet (1mg per tablet, 100 tablets per bottle)',
      'Storage: Store at room temperature in original packaging',
    ],
    coas: [
      { text: 'View Certificate of Analysis', href: 'https://www.forgeamino.com/s/FA-SLU022602.pdf' },
    ],
    inStock: true,
  },
  {
    id: 8,
    slug: '5-amino-1mq',
    name: '5-Amino-1MQ',
    price: 50.00,
    category: 'peptides',
    image: '/products/5-amino-1mq.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 5mg of 5-Amino-1MQ as an orange colored lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: '5-Amino-1MQ is a small molecule inhibitor of the enzyme nicotinamide N-methyltransferase (NNMT), which preserves NAD+ levels to enhance mitochondrial function, promote fat oxidation, and improve metabolic efficiency.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [],
    coas: [],
    inStock: true,
  },
  {
    id: 9,
    slug: 'tesamorelin',
    name: 'Tesamorelin',
    price: 85.00,
    category: 'peptides',
    image: '/products/tesamorelin.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg of Tesamorelin as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'Tesamorelin is a synthetic peptide analogue of GHRH with a trans-3-hexenoic acid moiety anchored at the N-terminus of its 44-amino acid sequence, providing enhanced stability compared to endogenous GHRH. The compound stimulates pituitary secretion of growth hormone and subsequently increases insulin-like growth factor-1 (IGF-1) and insulin-like growth factor binding protein-3 (IGFBP-3) levels in laboratory models. Emerging interests include metabolic health, fat loss, lean muscle preservation, improved lipid profiles, recovery, and brain function in non-HIV contexts.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₂₂₁H₃₆₆N₇₂O₅₇S',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View COA (Batch 012601)', href: 'https://www.forgeamino.com/s/FA-TSA012601.pdf' },
      { text: 'View COA (Batch 032601)', href: 'https://www.forgeamino.com/s/COA-TESA-FA-032601.pdf' },
    ],
    inStock: true,
  },
  {
    id: 10,
    slug: 'ipamorelin',
    name: 'Ipamorelin',
    price: 70.00,
    category: 'peptides',
    image: '/products/ipamorelin.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg of Ipamorelin as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'Ipamorelin is a synthetic pentapeptide functioning as a selective ghrelin mimetic and growth hormone secretagogue receptor (GHSR-1a) agonist. It selectively stimulates pituitary growth hormone (GH) release via GHSR activation, increasing cAMP and PKA while minimizing effects on cortisol, ACTH, prolactin, appetite, or gastric motility compared to other agonists. Key properties include a ~2-hour plasma half-life, renal excretion, stability when refrigerated, and subcutaneous bioavailability. Ipamorelin supports applications like GH stimulation, body composition improvement, sleep enhancement, and bone density.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₃₈H₄₉N₉O₅',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View COA (Batch 012601)', href: 'https://www.forgeamino.com/s/FA-IPA012601.pdf' },
      { text: 'View COA (Batch 032601)', href: 'https://www.forgeamino.com/s/COA-Ipa-FA-032601.pdf' },
    ],
    inStock: true,
  },
  {
    id: 11,
    slug: 'klow-blend',
    name: 'KLOW Blend',
    price: 185.00,
    category: 'blends',
    image: '/products/klow-blend.jpg',
    tagline: 'KLOW Blend 80mg (GHK-Cu 50mg, BPC-157 10mg, TB-500 10mg, KPV 10mg). This research only product is supplied in a 3ml vial containing a blend of GHK-Cu 50mg, BPC-157 10mg, TB-500 10mg and KPV 10mg (KLOW 80mg) as a lyophilized powder. The powder will generally have a purple color due to the copper content. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'KLOW Blend is an injectable research formulation combining four peptides — GHK-Cu, KPV, BPC-157, and TB-500 — studied for their synergistic effects on tissue regeneration, angiogenesis, collagen production, and inflammation reduction. GHK-Cu stimulates collagen and elastin synthesis, promotes fibroblast activity and gene expression for tissue remodeling. KPV inhibits NF-κB signaling and downregulates pro-inflammatory cytokines, reducing inflammation and promoting immune tolerance. BPC-157 enhances angiogenesis, boosts collagen production in tendons and ligaments, and protects gastrointestinal mucosa. TB-500 regulates actin polymerization for cell migration, supports new blood vessel formation, and coordinates cellular repair.',
    additionalInfo: '',
    mechanisms: [
      'Tissue Repair & Regeneration: BPC-157 and TB-500 accelerate fibroblast proliferation, collagen deposition, and cell migration to injury sites, while GHK-Cu provides structural extracellular matrix support.',
      'Angiogenesis & Circulation: GHK-Cu, BPC-157, and TB-500 upregulate VEGF, nitric oxide, and endothelial growth factors for improved vascularization across multiple tissue types.',
      'Anti-Inflammatory Effects: KPV primarily blocks inflammatory cascades (NF-κB, TNF-α, IL-1β), complemented by oxidative stress reduction from the other peptides, producing synergistic anti-inflammatory activity.',
      'Collagen & Skin Remodeling: GHK-Cu activates copper-dependent enzymes driving collagen and elastin synthesis and skin remodeling, studied in the context of wound healing and dermal rejuvenation.',
      'Pleiotropic Synergy: Targets overlapping pathways for recovery in preclinical models of skin, muscle, connective tissue, and gut healing — broader than any individual peptide alone.',
    ],
    technicalData: [
      'Form: Lyophilized powder (typically purple in color due to copper)',
      'GHK-Cu Molecular Formula: C₁₄H₂₃CuN₆O₄',
      'BPC-157 Molecular Formula: C₆₂H₉₈N₁₆O₂₂',
      'TB-500 Molecular Formula: C₂₁₂H₃₅₀N₅₆O₇₈S',
      'KPV Molecular Formula: C₁₆H₃₀N₄O₄',
      'Storage: Protect from light and moisture, keep tightly sealed. Refrigerate reconstituted solution.',
    ],
    coas: [
      { text: 'View Certificate of Analysis – Batch 022602', href: 'https://www.forgeamino.com/s/FA-KLO022602.pdf' },
    ],
    inStock: true,
  },
  {
    id: 12,
    slug: 'thymosin-alpha-1-10mg',
    name: 'Thymosin Alpha-1 10MG',
    price: 78.00,
    category: 'peptides',
    image: '/products/thymosin-alpha-1.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg of Thymosin Alpha-1 as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: '',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution.',
    ],
    coas: [],
    inStock: true,
    comingSoon: true,
  },
  {
    id: 13,
    slug: 'bpc-157',
    name: 'BPC-157',
    price: 70.00,
    category: 'peptides',
    image: '/products/bpc-157.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg of BPC-157 as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'BPC-157, a synthetic pentadecapeptide derived from human gastric juice, promotes healing through multiple interconnected mechanisms, primarily by stimulating angiogenesis, modulating nitric oxide pathways, enhancing growth factor signaling, and upregulating genes involved in tissue repair and anti-inflammation.',
    additionalInfo: '',
    mechanisms: [
      'Angiogenesis and Vascular Effects: Binds to VEGFR2 receptors on endothelial cells, triggering the Akt-eNOS pathway to boost nitric oxide production, dilate blood vessels, and enhance circulation and new vessel formation to injured areas.',
      'Nitric Oxide Modulation: By upregulating Nos3 (eNOS) and Nos1 while suppressing Nos2 (iNOS), BPC-157 improves endothelial function, counteracts ischemia/reperfusion injury, and promotes reperfusion in damaged tissues.',
      'Growth Hormone and Cellular Signaling: Increases growth hormone receptor expression in tendon fibroblasts, potentiating cell proliferation via JAK-2 activation. Also activates FAK-paxillin complexes for cell migration during wound healing.',
      'Gene Expression and Repair: Upregulates genes like Egr1 and Vegfr2 for vascularization, speeds cellular regeneration, and supports anti-inflammatory effects.',
      'Antioxidant and Protective Roles: Its structure (four carboxylic groups) enables reactive oxygen species scavenging, maintaining vascular integrity and reversing injurious cycles.',
    ],
    tissueEffects: [
      'Musculoskeletal: Joints, ligaments, tendons, muscles, and fractures via upregulated cell growth, proliferation, survival, and angiogenesis.',
      'Gut and CNS: Cytoprotection, mucosal integrity, and recovery from reperfusion disturbances.',
    ],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₆₂H₉₈N₁₆O₂₂',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View Certificate of Analysis', href: 'https://www.forgeamino.com/s/FA-BPC022602.pdf' },
    ],
    inStock: true,
  },
  {
    id: 14,
    slug: 'tb-500',
    name: 'TB-500',
    price: 70.00,
    category: 'peptides',
    image: '/products/tb-500.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10mg of TB-500 as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'TB-500, a synthetic analog of thymosin beta-4 (TB4), primarily acts by binding to G-actin monomers to regulate actin polymerization, enhancing cell migration, tissue repair, and angiogenesis. This mechanism supports wound healing, reduces inflammation, and promotes vascular development across various tissues.',
    additionalInfo: '',
    mechanisms: [
      'Actin Regulation: TB-500 binds globular actin (G-actin), preventing its polymerization into filamentous actin (F-actin), which increases actin monomer availability for dynamic cytoskeletal reorganization, cell motility, and migration to injury sites.',
      'Angiogenesis Promotion: Upregulates vascular endothelial growth factor (VEGF), stimulates endothelial cell sprouting and tube formation, and stabilizes new capillaries to improve blood flow and nutrient delivery to damaged tissues.',
      'Anti-Inflammatory Effects: Reduces pro-inflammatory cytokines (e.g., TNF-α, IL-1β, IL-6), suppresses NF-κB activation, and shifts macrophage polarization toward an anti-inflammatory M2 phenotype.',
      'Growth Factor and Signaling Pathways: Activates Akt/PI3K for cell survival, enhances ERK1/2 and p38 MAPK signaling, upregulates hepatocyte growth factor (HGF), and promotes stem cell mobilization and differentiation.',
    ],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₃₈H₆₈N₁₀O₁₄',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution',
    ],
    coas: [
      { text: 'View Certificate of Analysis', href: 'https://www.forgeamino.com/s/FA-TB5022602.pdf' },
    ],
    inStock: true,
  },
  {
    id: 15,
    slug: 'epithalon-50mg',
    name: 'Epithalon 50MG',
    price: 140.00,
    category: 'peptides',
    image: '/products/epithalon.jpg',
    tagline: 'Epithalon 50MG. This research only product is supplied in a 3ml vial containing 50mg of Epithalon as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'Epithalon (Epitalon) is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) derived from the natural peptide Epithalamin, originally isolated from the pineal gland. It has been extensively studied for its anti-aging properties, particularly its ability to activate telomerase and lengthen telomeres — the protective caps on chromosomes associated with cellular aging and longevity. Epithalon also modulates the neuroendocrine system and has demonstrated antioxidant and epigenetic regulatory effects in preclinical research.',
    additionalInfo: '',
    mechanisms: [
      'Telomerase Activation: Stimulates the enzyme telomerase, which elongates telomeres, potentially slowing cellular senescence and extending cellular lifespan.',
      'Antioxidant Effects: Reduces oxidative stress by upregulating antioxidant enzyme activity, protecting cells from free radical damage.',
      'Circadian Rhythm Regulation: Interacts with the pineal gland to normalize melatonin secretion and restore circadian rhythm function, particularly in aged subjects.',
      'Epigenetic Modulation: Influences gene expression patterns associated with aging, potentially reversing some age-related epigenetic changes.',
      'Neuroendocrine Regulation: Modulates hypothalamic-pituitary signaling, supporting hormonal balance and immune function in preclinical models.',
    ],
    technicalData: [
      'Form: Lyophilized powder',
      'Molecular Formula: C₁₄H₂₂N₄O₉',
      'Sequence: Ala-Glu-Asp-Gly (tetrapeptide)',
      'Storage: Protect from light and moisture, keep tightly sealed. Refrigerate reconstituted solution and use within 28 days.',
    ],
    coas: [],
    inStock: true,
  },
  {
    id: 16,
    slug: 'pinealon-20mg',
    name: 'Pinealon 20MG',
    price: 75.00,
    category: 'peptides',
    image: '/products/pinealon.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 20mg of Pinealon as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: '',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Molecular Formula: C₂₂H₃₆N₈O₅',
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution.',
    ],
    coas: [],
    inStock: true,
    comingSoon: true,
  },
  {
    id: 17,
    slug: '5-amino-1mq-capsules',
    name: '5-Amino-1MQ Capsules',
    price: 175.00,
    category: 'capsules',
    image: '/products/5-amino-1mq-capsules.jpg',
    tagline: 'This research only product is supplied as an orange colored tablet containing 70mg of 5-Amino-1MQ small molecule. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the bottle.',
    description: '5-Amino-1MQ is a small molecule inhibitor of the enzyme nicotinamide N-methyltransferase (NNMT), which preserves NAD+ levels to enhance mitochondrial function, promote fat oxidation, and improve metabolic efficiency.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [],
    coas: [],
    inStock: true,
  },
  {
    id: 18,
    slug: 'bpc-157-500mcg-tablets',
    name: 'BPC-157 500MCG Tablets',
    price: 0.00,
    category: 'tablets',
    image: '/products/bpc-157-tablets.jpg',
    tagline: 'BPC-157 500mcg oral tablets. This research only product is supplied as oral tablets containing 500mcg of BPC-157 per tablet. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity.',
    description: 'BPC-157 (Body Protection Compound-157) is a synthetic pentadecapeptide derived from a protective protein found in human gastric juice. In oral tablet form, BPC-157 is studied for its potential systemic and gastrointestinal protective effects, promoting healing through multiple interconnected mechanisms, primarily by stimulating angiogenesis, modulating nitric oxide pathways, enhancing growth factor signaling, and upregulating genes involved in tissue repair and anti-inflammation.',
    additionalInfo: '',
    mechanisms: [
      'VEGFR2 and Angiogenesis: BPC-157 upregulates VEGFR2 expression, stimulating the formation of new blood vessels and accelerating healing of damaged tissues.',
      'Akt-eNOS Pathway: Activates the Akt/eNOS signaling cascade to enhance nitric oxide production, improving blood flow and reducing oxidative stress in tissues.',
      'Nitric Oxide Modulation: Modulates nitric oxide synthesis to maintain vascular tone and promote tissue perfusion, essential for repair in musculoskeletal and gastrointestinal structures.',
      'Growth Hormone Sensitization: Enhances growth hormone receptor expression and sensitizes tissues to GH signaling, facilitating anabolic and regenerative processes.',
      'Gene Expression and Anti-Inflammation: Upregulates genes associated with repair and cytoprotection while downregulating pro-inflammatory mediators, supporting systemic recovery.',
    ],
    tissueEffects: [
      'Gut and Gastrointestinal: Studied for its ability to heal intestinal epithelial damage, reduce gut inflammation, and restore mucosal integrity in research models of inflammatory bowel conditions.',
      'Musculoskeletal: Research suggests BPC-157 may support the repair of tendons, ligaments, and muscle tissue by enhancing fibroblast activity and collagen synthesis.',
    ],
    technicalData: [
      'Form: Oral Tablet (500mcg per tablet)',
      'Molecular Formula: C₆₂H₉₈N₁₆O₂₂',
      'Molecular Weight: 1419.5 g/mol',
      'Sequence: Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val',
      'Storage: Store at room temperature, away from direct light and moisture',
      'Purity: ≥99% (verified by independent 3rd party testing)',
    ],
    coas: [],
    inStock: false,
  },
  {
    id: 19,
    slug: 'hgh-191aa-10iu-x-10-vials',
    name: 'HGH 191AA (10IU x 10 Vials)',
    price: 220.00,
    category: 'peptides',
    image: '/products/hgh-191aa.jpg',
    tagline: 'This research only product is supplied in a 3ml vial containing 10IU as a lyophilized powder. Every compound undergoes stringent independent 3rd party testing in a US laboratory with verified 99%+ purity and QR link to the COA stamped on the vial.',
    description: 'All products made available on this website are intended exclusively for research and development purposes and are strictly not for human consumption or therapeutic use.',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [
      'Storage: Protect from light and moisture, keep tightly sealed, refrigerate reconstituted solution.',
    ],
    coas: [],
    inStock: true,
  },
  // ── Lab-only products ────────────────────────────────────────────────────
  // Hidden from /shop; visible on /lab after unlock. qbo_name is the exact
  // QuickBooks inventory item name so sales decrement the correct SKU.
  {
    id: 20,
    slug: 'r',
    name: 'R',
    price: 195.00,
    category: 'lab',
    image: null,
    qbo_name: 'GLP3-R 20mg',
    tagline: '',
    description: '',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [],
    coas: [],
    inStock: true,
    hidden: true,
  },
  {
    id: 21,
    slug: 's',
    name: 'S',
    price: 60.00,
    category: 'lab',
    image: null,
    qbo_name: 'SS31',
    tagline: '',
    description: '',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [],
    coas: [],
    inStock: true,
    hidden: true,
  },
  {
    id: 22,
    slug: 't',
    name: 'T',
    price: 225.00,
    category: 'lab',
    image: null,
    qbo_name: 'GLP2-T 30mg',
    tagline: '',
    description: '',
    additionalInfo: '',
    mechanisms: [],
    technicalData: [],
    coas: [],
    inStock: true,
    hidden: true,
  },
]

export function getProductBySlug(slug) {
  return PRODUCTS.find(p => p.slug === slug) || null
}

export function getProductsByCategory(category) {
  return PRODUCTS.filter(p => p.category === category)
}

export function formatPrice(price) {
  if (price === 0) return 'Coming Soon'
  return `$${price.toFixed(2)}`
}
